---
name: chazy-dev

services:
  frontend:
    image: chazy-frontend:dev
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    command: npx vite --host 0.0.0.0
    environment:
      VITE_BACKEND_URL: 'TODO'
    volumes:
      - ../:/usr/app:rw
    ports:
      - 3000:3000
    restart: 'no'
